export const TYPE_MAP = {
  section: { letter: 'S', hue: '#c97d3c', label: 'Section' },
  container: { letter: 'C', hue: '#8a7d6b', label: 'Container' },
  div: { letter: 'D', hue: '#6b6b6b', label: 'Div' },
  heading: { letter: 'H', hue: '#b86e4a', label: 'Heading' },
  text: { letter: 'T', hue: '#7d8a6b', label: 'Text' },
  button: { letter: 'B', hue: '#c9a43c', label: 'Button' },
  grid: { letter: 'G', hue: '#6b7d8a', label: 'Grid' },
  image: { letter: 'I', hue: '#7dab6e', label: 'Image' },
  'flex-row': { letter: '↔', hue: '#8a6b7d', label: 'Flex Row' },
  'flex-column': { letter: '↕', hue: '#6b8a7d', label: 'Flex Col' },
  link: { letter: '↗', hue: '#7d6b8a', label: 'Link' },
  list: { letter: 'Li', hue: '#8a7d6b', label: 'List' },
  spacer: { letter: '—', hue: '#7a746e', label: 'Spacer' },
  divider: { letter: '÷', hue: '#7a746e', label: 'Divider' },
  video: { letter: 'V', hue: '#6b7d8a', label: 'Video' },
  icon: { letter: 'Ic', hue: '#8a847d', label: 'Icon' },
  'post-loop': { letter: '∞', hue: '#b86e4a', label: 'Post Loop' },
  'post-title': { letter: 'Pt', hue: '#b86e4a', label: 'Post Title' },
  'post-content': { letter: 'Pc', hue: '#b86e4a', label: 'Post Content' },
  'post-meta': { letter: 'Pm', hue: '#b86e4a', label: 'Post Meta' },
  'featured-image': { letter: 'Fi', hue: '#b86e4a', label: 'Featured Image' },
  menu: { letter: 'M', hue: '#c97d3c', label: 'Menu' },
  'tekton-field': { letter: '◆', hue: '#c97d3c', label: 'Field' },
  'search-form': { letter: 'Sf', hue: '#b86e4a', label: 'Search' },
};

export const ELEMENT_CATEGORIES = [
  {
    name: 'Structure',
    items: [
      { type: 'section', desc: 'Full-width section wrapper' },
      { type: 'container', desc: 'Contained width wrapper' },
      { type: 'grid', desc: 'CSS Grid layout' },
      { type: 'flex-row', desc: 'Horizontal flex container' },
      { type: 'flex-column', desc: 'Vertical flex container' },
    ],
  },
  {
    name: 'Basic',
    items: [
      { type: 'heading', desc: 'H1–H6 heading' },
      { type: 'text', desc: 'Paragraph / rich text' },
      { type: 'image', desc: 'Single image' },
      { type: 'button', desc: 'Button / CTA' },
      { type: 'link', desc: 'Text link' },
      { type: 'icon', desc: 'SVG icon' },
      { type: 'list', desc: 'Ordered / unordered list' },
      { type: 'video', desc: 'Embed or self-hosted' },
      { type: 'divider', desc: 'Horizontal rule' },
      { type: 'spacer', desc: 'Vertical spacing' },
    ],
  },
  {
    name: 'WordPress',
    items: [
      { type: 'post-loop', desc: 'WP_Query post loop' },
      { type: 'post-title', desc: 'Post title' },
      { type: 'post-content', desc: 'Post content' },
      { type: 'post-meta', desc: 'Post date/author/cats' },
      { type: 'featured-image', desc: 'Featured image' },
      { type: 'menu', desc: 'Navigation menu' },
      { type: 'tekton-field', desc: 'Tekton/ACF field value' },
      { type: 'search-form', desc: 'Search form' },
    ],
  },
];
